// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ImageFailureCode string

const (
	ImageFailureCode_ImageNotFound                 ImageFailureCode = "ImageNotFound"
	ImageFailureCode_ImageReferencedByManifestList ImageFailureCode = "ImageReferencedByManifestList"
	ImageFailureCode_ImageTagDoesNotMatchDigest    ImageFailureCode = "ImageTagDoesNotMatchDigest"
	ImageFailureCode_InvalidImageDigest            ImageFailureCode = "InvalidImageDigest"
	ImageFailureCode_InvalidImageTag               ImageFailureCode = "InvalidImageTag"
	ImageFailureCode_KmsError                      ImageFailureCode = "KmsError"
	ImageFailureCode_MissingDigestAndTag           ImageFailureCode = "MissingDigestAndTag"
)

type LayerAvailability string

const (
	LayerAvailability_AVAILABLE   LayerAvailability = "AVAILABLE"
	LayerAvailability_UNAVAILABLE LayerAvailability = "UNAVAILABLE"
)

type LayerFailureCode string

const (
	LayerFailureCode_InvalidLayerDigest LayerFailureCode = "InvalidLayerDigest"
	LayerFailureCode_MissingLayerDigest LayerFailureCode = "MissingLayerDigest"
)

type RegistryAliasStatus string

const (
	RegistryAliasStatus_ACTIVE   RegistryAliasStatus = "ACTIVE"
	RegistryAliasStatus_PENDING  RegistryAliasStatus = "PENDING"
	RegistryAliasStatus_REJECTED RegistryAliasStatus = "REJECTED"
)
